language: go
sudo: false
matrix:
  include:
  - go: 1.x
before_install:
- go get github.com/mitchellh/gox
install:
- 
script:
- go get -t -v ./...
- go vet $(go list ./... | grep -v /vendor/)
- go test -v -race ./...
- gox -os="linux darwin windows" -arch="amd64" -output="auth.{{.OS}}.{{.Arch}}" 
  -ldflags "-X main.Rev=`git rev-parse --short HEAD`" -verbose ./...
deploy:
  provider: releases
  api_key:
    secure: pGHsgcGpc9Q7UQoKdUuNNLzio7b4fi6Akc/di1rjDyG/800kh6X2EaNAfd12mkSWludlv0Zj2WZnQpQvorNOoDNnQgU/5KxdFFBz7qRXIjk0IV7iiOzHVVqPBftCrqhBWcfB+nOG5S1nY9QUtYbVfJcoxrShohW2xNc0C7CAFSCXvByHcD/ovWygAvdHxEGyfywC1sjomHY1NJvMk5kNtNJ1twur2S0VbE5+d+M9eqnlHkhAhMhOgCpyYS7Egu2Q2TPOU12kO6uGCC8Gtsru+LHAhRGQHAMUCB9gHJM3+MKknnAfm+Q2JELGUY7flR/KluII51AejN8oq7WMGi36ZQunbyRihs1yBFDmPl9iRESoBEAI+wE0gTk9WqCOViaAiOsoXzIwYjaacJ81cfU3kEAeOU3w88S5N86PfSxri7/uG77eD4GizjqiZJ9JFA2QOzZCeIU5icnK75/URoxywZ1tXFZFsA2X4d5NaelW0hLEdXrC6fAB5+Qo8/NsTuHV8+PjKGbZ7Sm2avqTQ2nJSNZeur2GUh4bfMsw/MsD9ysYpzkthc5PsCH+Dtfzskqg1scgzYy2wTkkt4u9xU6W/iuB84NTXLOn94PQARG83wrIafDlaEgjpBJMMN3e/prr3P8Q+hf7N29ko+CE5RytjW1nwW7+Xkn/iRPxNoyHDoU=
  file:
    - auth.windows.amd64.exe
    - auth.darwin.amd64
    - auth.linux.amd64
  on:
    repo: go-park-mail-ru/2018_2_LSP_AUTH
